name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build main
      run: go build -v ./cmd/api/server/main.go
    
    - name: Build proxy_server
      run: go build -v go build -v ./cmd/proxy_server/proxy_server.go

    - name: Test
      run: go test -v ./...
